### ISSUE TITLE
Agent Connection Timeout

### ISSUE THREAD

**Issue by 0x15f** [blackfireio/php-sdk#32]
Exception:
```
Fatal error: Uncaught Blackfire\Exception\ApiException: 101: Agent connection timeout (read) in /root/node/vendor/blackfire/php-sdk/src/Blackfire/Exception/ApiException.php:18
Stack trace:
#0 /root/node/vendor/blackfire/php-sdk/src/Blackfire/Probe.php(85): Blackfire\Exception\ApiException::fromStatusCode('Agent connectio...', '101')
#1 /root/node/vendor/blackfire/php-sdk/src/Blackfire/Probe.php(58): Blackfire\Probe->checkError()
#2 /root/node/vendor/blackfire/php-sdk/src/Blackfire/Client.php(62): Blackfire\Probe->enable()
#3 /root/node/src/node/NodeServer.php(27): Blackfire\Client->createProbe()
#4 {main}
  thrown in /root/node/vendor/blackfire/php-sdk/src/Blackfire/Exception/ApiException.php on line 18
```

Code:
```php
$probe = \BlackfireProbe::getMainInstance();
$probe->disable();

$blackfire = new \Blackfire\Client();
$probe = $blackfire->createProbe();

//run stuff

$profile = $blackfire->endProbe($probe);
var_dump($profile->getUrl());
```

**Comment by romainneutron** [comment]
Please reopen if needed
